-- phase2-schema-and-migration.sql
-- Path: ~/coworker/parks/db/phase2-schema-and-migration.sql
-- Desc: Sullivan Parks Phase 2 — unified content schema, parks entity,
--       RLS policies, and one-shot migration of existing events.
-- Run each STAGE separately in Supabase SQL Editor. Verify between stages.
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- STAGE 1 — Create parks entity table
-- ════════════════════════════════════════════════════════════
-- Run this block alone first. Verify with the SELECT at the bottom.

CREATE TABLE IF NOT EXISTS parks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL,
  slug        text NOT NULL UNIQUE,
  lat         numeric,
  lng         numeric,
  description text,
  cover_url   text,
  sort_order  int DEFAULT 100,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

CREATE INDEX parks_slug_idx ON parks (slug);
CREATE INDEX parks_sort_idx ON parks (sort_order, name);

ALTER TABLE parks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read parks"     ON parks FOR SELECT USING (true);
CREATE POLICY "admin all parks"       ON parks FOR ALL    USING (auth.role() = 'authenticated');

-- Verify
SELECT 'parks table created' AS status,
       COUNT(*) AS row_count FROM parks;


-- ════════════════════════════════════════════════════════════
-- STAGE 2 — Create content table (unified)
-- ════════════════════════════════════════════════════════════
-- Run only AFTER stage 1 succeeds.

CREATE TABLE IF NOT EXISTS content (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        text NOT NULL CHECK (type IN ('event', 'program', 'news', 'park_info')),
  title       text NOT NULL,
  slug        text NOT NULL,
  summary     text,
  body_html   text,
  cover_url   text,
  category    text DEFAULT 'General',
  status      text NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'archived')),
  park_id     uuid REFERENCES parks(id) ON DELETE SET NULL,
  start_at    timestamptz,
  end_at      timestamptz,
  location    text,
  extras      jsonb DEFAULT '{}'::jsonb,
  archived_at timestamptz,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),

  -- slugs unique within a type, not globally; lets Programs and Events share slugs
  UNIQUE (type, slug)
);

-- Note: start_at, end_at, location are pulled OUT of `extras` and made into
-- real columns because they're used by Events AND Programs AND can appear in
-- public listing queries ("upcoming events", "summer programs"). JSONB indexing
-- works but real columns are simpler. Everything else type-specific goes in `extras`.

CREATE INDEX content_type_status_idx ON content (type, status, created_at DESC);
CREATE INDEX content_park_id_idx     ON content (park_id) WHERE park_id IS NOT NULL;
CREATE INDEX content_start_at_idx    ON content (start_at) WHERE start_at IS NOT NULL;

ALTER TABLE content ENABLE ROW LEVEL SECURITY;

-- Mirror the existing events policy pattern exactly (no model change)
CREATE POLICY "public read content"  ON content FOR SELECT USING (status = 'published');
CREATE POLICY "admin all content"    ON content FOR ALL    USING (auth.role() = 'authenticated');

-- Verify
SELECT 'content table created' AS status,
       COUNT(*) AS row_count FROM content;


-- ════════════════════════════════════════════════════════════
-- STAGE 3 — Migrate existing events into content
-- ════════════════════════════════════════════════════════════
-- Run only AFTER stages 1 and 2 succeed.
-- Wrapped in BEGIN/COMMIT so it's all-or-nothing.

BEGIN;

INSERT INTO content (
  id,            -- preserve the original bigint id so external URLs/bookmarks survive
  type,
  title,
  slug,
  summary,
  body_html,
  cover_url,
  category,
  status,
  start_at,
  end_at,
  location,
  created_at,
  updated_at,
  archived_at,
  extras
)
SELECT
  id,
  'event',
  title,
  slug,
  description,                 -- old `description` → new `summary`
  body,                        -- old `body` → new `body_html`
  cover_image_url,             -- only the active cover column; `cover_photo` ignored (all NULL)
  COALESCE(category, 'General'),
  CASE
    WHEN archived_at IS NOT NULL THEN 'archived'
    WHEN published = false        THEN 'archived'   -- decision: drafts collapse to archived
    ELSE 'published'
  END,
  start_at,
  end_at,
  location,
  created_at,
  updated_at,
  archived_at,
  '{}'::jsonb                  -- no extras for events; all fields are real columns
FROM events;

-- Reset the identity sequence on content so new rows continue from the right number
SELECT setval(
  pg_get_serial_sequence('content', 'id'),
  COALESCE((SELECT MAX(id) FROM content), 0)
);

-- Verify before committing
SELECT 'migration summary' AS check,
       (SELECT COUNT(*) FROM events)  AS source_event_rows,
       (SELECT COUNT(*) FROM content WHERE type = 'event') AS migrated_event_rows,
       (SELECT COUNT(*) FROM content WHERE type = 'event' AND status = 'published')  AS published,
       (SELECT COUNT(*) FROM content WHERE type = 'event' AND status = 'archived')   AS archived;

-- ─────────────────────────────────────────────────────────────
-- READ the row above. Expect:
--   source_event_rows  = 4
--   migrated_event_rows = 4
--   published          = 2
--   archived           = 2  (1 archived + 1 unpublished, both now archived)
--
-- If matches → run COMMIT below.
-- If does NOT match → run ROLLBACK; nothing changes.
-- ─────────────────────────────────────────────────────────────

COMMIT;  -- or ROLLBACK;


-- ════════════════════════════════════════════════════════════
-- STAGE 4 — Verify the new world works
-- ════════════════════════════════════════════════════════════
-- Run AFTER stage 3 commits. These are sanity checks.

-- Sample row should look identical to its events counterpart
SELECT * FROM content WHERE type = 'event' ORDER BY id DESC LIMIT 1;

-- All-types view (right now only events exist, but the query shape is the one
-- we'll use for the new ContentList component)
SELECT type, status, COUNT(*)
FROM content
GROUP BY type, status
ORDER BY type, status;

-- Parks table sanity (still empty until we seed)
SELECT * FROM parks;


-- ════════════════════════════════════════════════════════════
-- DO NOT YET — Stage 5 (drop old events table)
-- ════════════════════════════════════════════════════════════
-- Wait until application code is fully switched to read from `content` AND
-- has been running cleanly for ~1 week. Then run:
--
--   DROP TABLE events;
--
-- Until then, `events` stays as the safety net we can read from / restore from
-- if anything goes wrong with the cutover. Don't rush this step.

-- end of file
